"""Build data/players.js for 2Kdle.

Input:
  scripts/source/players.csv  One row per player. Columns:
      name, team, ovr, pos, height_in, nation, birthdate,
      outside_scoring, inside_scoring, athleticism, playmaking, defense,
      rebounding, source, source_url
    team is the three-letter abbreviation (ATL, BOS, ... WAS), pos is one of
    PG/SG/SF/PF/C (the primary position), height_in is total inches, nation is
    the country name (see CONTINENT below), birthdate is YYYY-MM-DD and is only
    used to match the answer photo on Wikidata, never shown in the game.

  Right now that file is produced from the 2KRatings snapshot by
  scripts/import_2kratings.py. To switch to an official 2K list, write the
  same columns from the official data instead and rerun this script.

Output:
  data/players.js  A single `const RAW = [...]` array the game loads.

Row order matters: the daily puzzle picks a player by index, so rebuilding
with different data changes which player each day uses.

Usage:
  python3 scripts/build_data.py
"""

import csv
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "scripts" / "source" / "players.csv"
OUT = ROOT / "data" / "players.js"

EAST = {"ATL", "BOS", "BKN", "CHA", "CHI", "CLE", "DET", "IND", "MIA", "MIL", "NYK", "ORL", "PHI", "TOR", "WAS"}
WEST = {"DAL", "DEN", "GSW", "HOU", "LAC", "LAL", "MEM", "MIN", "NOP", "OKC", "PHX", "POR", "SAC", "SAS", "UTA"}
POSITIONS = {"PG", "SG", "SF", "PF", "C"}

# Continent used for the yellow "same continent" nationality clue. Countries
# that sit between continents follow their basketball federation zone
# (FIBA Europe for Turkey, Georgia and Israel).
CONTINENT = {
    "United States": "North America", "Canada": "North America", "Bahamas": "North America",
    "Puerto Rico": "North America", "Dominican Republic": "North America", "Haiti": "North America",
    "Jamaica": "North America", "Mexico": "North America", "Panama": "North America",
    "Brazil": "South America", "Argentina": "South America", "Venezuela": "South America",
    "France": "Europe", "Germany": "Europe", "Spain": "Europe", "Lithuania": "Europe",
    "United Kingdom": "Europe", "Turkey": "Europe", "Switzerland": "Europe", "Sweden": "Europe",
    "Slovenia": "Europe", "Serbia": "Europe", "Russia": "Europe", "Portugal": "Europe",
    "Montenegro": "Europe", "Latvia": "Europe", "Greece": "Europe", "Georgia": "Europe",
    "Finland": "Europe", "Croatia": "Europe", "Bosnia and Herzegovina": "Europe", "Belgium": "Europe",
    "Austria": "Europe", "Israel": "Europe", "Italy": "Europe", "Netherlands": "Europe",
    "Czech Republic": "Europe", "Poland": "Europe", "Ukraine": "Europe", "Estonia": "Europe",
    "Denmark": "Europe", "Hungary": "Europe", "Bulgaria": "Europe", "Romania": "Europe",
    "Nigeria": "Africa", "Cameroon": "Africa", "Senegal": "Africa", "South Sudan": "Africa",
    "DR Congo": "Africa", "Congo": "Africa", "Guinea": "Africa", "Mali": "Africa",
    "Uganda": "Africa", "Egypt": "Africa",
    "Australia": "Oceania", "New Zealand": "Oceania",
    "Japan": "Asia", "China": "Asia", "Philippines": "Asia", "Lebanon": "Asia",
}


def main():
    rows = []
    for r in csv.DictReader(open(SRC, encoding="utf-8")):
        team, pos, nation = r["team"], r["pos"], r["nation"]
        if team not in EAST | WEST:
            raise SystemExit(f"Unknown team {team!r} for {r['name']}")
        if pos not in POSITIONS:
            raise SystemExit(f"Unknown position {pos!r} for {r['name']}")
        if nation not in CONTINENT:
            raise SystemExit(f"Add {nation!r} to CONTINENT (player {r['name']})")
        rows.append([
            r["name"], int(r["ovr"]), pos, team, "East" if team in EAST else "West",
            nation, CONTINENT[nation], int(r["height_in"]),
            int(r["outside_scoring"]), int(r["inside_scoring"]), int(r["athleticism"]),
            int(r["playmaking"]), int(r["defense"]), int(r["rebounding"]),
            int(r["birthdate"][:4]) if r["birthdate"] else 0,
        ])

    # Two players sharing a name get their team appended.
    counts = Counter(row[0] for row in rows)
    for row in rows:
        if counts[row[0]] > 1:
            row[0] = f"{row[0]} ({row[3]})"

    sources = sorted({r["source"] for r in csv.DictReader(open(SRC, encoding="utf-8"))})
    header = (
        "// Generated by scripts/build_data.py. Do not edit by hand.\n"
        f"// Source: {'; '.join(sources)}\n"
        "// Row: [name, ovr, pos, team, conference, nation, continent, height (in), "
        "outside, inside, athleticism, playmaking, defense, rebounding, birth year]\n"
    )
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(header + "const RAW = " + json.dumps(rows, ensure_ascii=False, separators=(",", ":")) + ";\n", encoding="utf-8")
    print(f"Wrote {len(rows)} players to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
